# Generated by Django 3.1.3 on 2020-11-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=200, verbose_name='rut')),
                ('descripcion', models.CharField(max_length=200, verbose_name='descripcion')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='ubicacion')),
                ('razon', models.CharField(max_length=200, verbose_name='razon')),
            ],
        ),
    ]
