# Generated by Django 3.1.3 on 2020-11-11 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='persona_juridica',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('rut_dv', models.CharField(blank=True, max_length=1, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('rut_dv', models.CharField(blank=True, max_length=1, null=True)),
                ('ape_pat', models.CharField(blank=True, max_length=30, null=True)),
                ('ape_mat', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_calle', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_numero', models.CharField(blank=True, max_length=30, null=True)),
                ('comuna_cod_comu', models.IntegerField()),
                ('perfil_id', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='persona_juridica_usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('persona_juridic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_juridic', to='webapp.persona_juridica')),
                ('usuario_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_rut', to='webapp.usuario')),
            ],
            options={
                'unique_together': {('usuario_rut', 'persona_juridic')},
            },
        ),
    ]
