# Generated by Django 3.1.3 on 2020-11-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_persona_juridica_persona_juridica_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona_juridica_usuario',
            name='tipo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
