# Generated by Django 3.1.3 on 2020-11-11 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_comuna_provincia_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona_juridica_usuario',
            name='persona_juridic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_juridica_usuario', to='webapp.persona_juridica'),
        ),
        migrations.AlterField(
            model_name='persona_juridica_usuario',
            name='usuario_rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_persona_juridica', to='webapp.usuario'),
        ),
    ]
