# Generated by Django 3.1.3 on 2020-11-13 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20201112_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona_juridica_usuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='persona_juridica_usuario',
            name='persona_juridic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_juridic', to='webapp.persona_juridica'),
        ),
        migrations.AlterField(
            model_name='persona_juridica_usuario',
            name='usuario_rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='webapp.usuario'),
        ),
    ]
