# Generated by Django 3.1.2 on 2020-11-13 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20201113_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona_juridica_usuario',
            name='usuario_rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_track', to='webapp.usuario'),
        ),
    ]
