# Generated by Django 3.1.2 on 2020-11-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20201113_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='direccion_via',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
    ]
