# Generated by Django 3.1.2 on 2020-11-16 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_direccion_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona_juridica_usuario',
            name='persona_juridic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_juridic_track', to='webapp.persona_juridica'),
        ),
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_tramite', models.CharField(blank=True, max_length=45, null=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('total_terreno', models.CharField(blank=True, max_length=45, null=True)),
                ('superficie_util', models.CharField(blank=True, max_length=45, null=True)),
                ('superficie_edificada', models.CharField(blank=True, max_length=45, null=True)),
                ('rut_pertenece', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
                ('comuna_cod_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_Comuna', to='webapp.comuna')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_usuario', to='webapp.usuario')),
            ],
        ),
    ]
