# Generated by Django 3.1.2 on 2020-11-17 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20201117_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona_juridica',
            name='documentos_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='documentos_secondary', to='webapp.documentos'),
            preserve_default=False,
        ),
    ]
