# Generated by Django 3.1.2 on 2020-11-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_tipo_area_tipo_arteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='cant_periodo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cant', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ficha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo_ficha', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_creacion', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='flujo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='imiv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vigencia', models.DateTimeField(null=True)),
                ('entrada_viajes', models.CharField(blank=True, max_length=45, null=True)),
                ('salida_viajes', models.CharField(blank=True, max_length=45, null=True)),
                ('entrada_vehiculo', models.CharField(blank=True, max_length=45, null=True)),
                ('salida_vehiculos', models.CharField(blank=True, max_length=45, null=True)),
                ('flujo_vehicular', models.CharField(blank=True, max_length=45, null=True)),
                ('flujo_viajes', models.CharField(blank=True, max_length=45, null=True)),
                ('categoria_flujo_vehicular', models.CharField(blank=True, max_length=45, null=True)),
                ('categoria_flujo_viajes', models.CharField(blank=True, max_length=45, null=True)),
                ('intersecciones_vehicular', models.CharField(blank=True, max_length=45, null=True)),
                ('interseccionas_viajes', models.CharField(blank=True, max_length=45, null=True)),
                ('area_influencia_vehicular', models.CharField(blank=True, max_length=45, null=True)),
                ('area_influencia_viajes', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='periodo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='proyecto_dproyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cant_habitaciones', models.CharField(blank=True, max_length=45, null=True)),
                ('num_habitaciones', models.CharField(blank=True, max_length=45, null=True)),
                ('cant_personas', models.CharField(blank=True, max_length=45, null=True)),
                ('cant_dispensadores', models.CharField(blank=True, max_length=45, null=True)),
                ('num_asientos', models.CharField(blank=True, max_length=45, null=True)),
                ('num_estudiantes', models.CharField(blank=True, max_length=45, null=True)),
                ('num_viviendas', models.CharField(blank=True, max_length=45, null=True)),
                ('num_estacionamientos', models.CharField(blank=True, max_length=45, null=True)),
                ('num_lineas_revision', models.CharField(blank=True, max_length=45, null=True)),
                ('num_darsenas', models.CharField(blank=True, max_length=45, null=True)),
                ('total_servicios', models.CharField(blank=True, max_length=45, null=True)),
                ('inc_servicios_movimiento', models.CharField(blank=True, max_length=45, null=True)),
                ('escala', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='servicio_infraestructura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tasas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tramo', models.CharField(blank=True, max_length=45, null=True)),
                ('tasa', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_vigencia', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tasas_proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tramo', models.CharField(blank=True, max_length=45, null=True)),
                ('tasa', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
