# Generated by Django 3.1.2 on 2020-11-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20201119_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona_juridica_usuario',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='direccion_rol',
            name='direccion_via_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='direccion_rol_direccion_via', to='webapp.direccion_via'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion_rol',
            name='rol_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='direccion_rol_rol', to='webapp.rol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion_rol',
            name='tipo_area_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='direccion_rol_tipo_area', to='webapp.tipo_area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='direccion_rol',
            name='tipo_arteria_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='direccion_rol_tipo_arteria', to='webapp.tipo_arteria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona_juridica_usuario',
            name='documentos_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_juridica_usuario_documentos', to='webapp.documentos'),
        ),
        migrations.AddField(
            model_name='rol_proyecto',
            name='proyecto_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rol_proyecto_proyecto', to='webapp.proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rol_proyecto',
            name='rol_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rol_proyecto_rol', to='webapp.rol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiculos_equivalente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
