# Generated by Django 3.1.2 on 2020-11-19 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20201119_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona_juridica_usuario',
            old_name='documentos_id',
            new_name='documento_legal_documentos_id',
        ),
        migrations.RemoveField(
            model_name='vehiculos_equivalente',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='cant_periodo',
            name='periodo_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cant_periodo_periodo', to='webapp.periodo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cant_periodo',
            name='servicio_infraestructura_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cant_periodo_servicio_infraestructura', to='webapp.servicio_infraestructura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='certificado_documentos_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='webapp.documentos'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='oficiio_documentos_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='webapp.documentos'),
        ),
        migrations.AddField(
            model_name='imiv',
            name='ficha_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='imiv_ficha', to='webapp.ficha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log_proyecto',
            name='proyecto_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='log_proyecto_proyecto', to='webapp.proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona_juridica',
            name='comuna_cod_comuna',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='persona_juridica_comuna', to='webapp.comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona_juridica',
            name='direccion_via_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='persona_juridica_direccion_via', to='webapp.direccion_via'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona_proyecto',
            name='comuna_cod_comuna',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='persona_proyecto_comuna', to='webapp.comuna'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona_proyecto',
            name='estado',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='persona_proyecto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='persona_proyecto',
            name='proyecto_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='persona_proyecto_proyecto', to='webapp.proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona_proyecto',
            name='tipo_participante_empresa_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='persona_proyecto_tipo_participante_empresa', to='webapp.tipo_participante_empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='direccion_principal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_direccion_rol', to='webapp.direccion_rol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='proyecto_padre_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto_dproyecto',
            name='dproyecto_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_dproyecto_dproyecto', to='webapp.dproyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto_dproyecto',
            name='proyecto_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_dproyecto_proyecto', to='webapp.proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto_ficha',
            name='declaracion_proy_conjunto_documentos_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declaracion_proy_conjunto_documentos_id', to='webapp.documentos'),
        ),
        migrations.AddField(
            model_name='proyecto_ficha',
            name='ficha_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_ficha_ficha', to='webapp.ficha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto_ficha',
            name='proyecto_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_ficha_proyecto', to='webapp.proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio_infraestructura',
            name='proyecto_dproyecto_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='servicio_infraestructura_proyecto_dproyecto', to='webapp.proyecto_dproyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio_infraestructura',
            name='vehiculos_equivalente_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='servicio_infraestructura_vehiculos_equivalente', to='webapp.vehiculos_equivalente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasas',
            name='dproyecto_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tasas_dproyecto', to='webapp.dproyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasas',
            name='flujo_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tasas_flujo', to='webapp.flujo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasas',
            name='periodo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasas_periodo', to='webapp.periodo'),
        ),
        migrations.AddField(
            model_name='tasas_proyecto',
            name='flujo_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tasas_proyecto_flujo', to='webapp.flujo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasas_proyecto',
            name='periodo_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tasas_proyecto_periodo', to='webapp.periodo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasas_proyecto',
            name='proyecto_dproyecto_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tasas_proyecto_proyecto_dproyecto', to='webapp.proyecto_dproyecto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log_proyecto',
            name='usuario_rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_proyecto_usuario', to='webapp.usuario'),
        ),
        migrations.AlterField(
            model_name='persona_juridica',
            name='acto_constitutivo_documentos_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_juridica_documentos', to='webapp.documentos'),
        ),
    ]
