# Generated by Django 3.1.2 on 2020-11-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20201119_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona_proyecto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='persona_proyecto',
            name='fecha_creacion',
        ),
    ]
